In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from tensorflow import keras

In [3]:
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.compile(optimizer='Adam', loss='mean_absolute_error')

In [5]:
xs = np.array([-1, 0, 1, 2, 3, 4], dtype=float)
ys = np.array([-3, -1, 1, 3, 5, 7], dtype=float)

In [6]:
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 872ms/step - loss: 4.8663
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 4.8641
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 4.8620
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 4.8598
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 4.8576
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4.8555
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 4.8533
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4.8511
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 4.8490
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 4.8468
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 4.8446
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 4.8425
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 4.8403
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4.8381
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 4.8360
Epoch 16/500
1/1 ━

In [10]:
model.predict(x=np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[-2.8617463]], dtype=float32)

In [12]:
model.compile(optimizer='Adam', loss='mean_squared_error')
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 611ms/step - loss: 19.9354
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 19.9118
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 19.8881
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 19.8645
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 19.8410
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 19.8174
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 19.7939
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 19.7703
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 19.7468
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 19.7234
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 19.6999
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 19.6765
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 19.6530
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 19.6296
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 19.6063
Epo

In [13]:
model.predict(x=np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[2.1658304]], dtype=float32)

In [14]:
model.compile(optimizer='sgd', loss='mean_squared_error')
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 282ms/step - loss: 11.0566
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 9.2727
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 7.8574
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 6.7324
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 5.8360
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5.1196
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4.5452
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 4.0826
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 3.7083
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - loss: 3.4036
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 3.1539
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 2.9477
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 2.7758
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.6313
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 2.5083
Epoch 16/500
1/1

In [15]:
model.predict(x=np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[18.971613]], dtype=float32)

In [16]:
model.compile(optimizer='sgd', loss='mean_absolute_error')
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 272ms/step - loss: 0.0078
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0087
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0210
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0171
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.0210
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0171
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - loss: 0.0210
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.0171
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.0210
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0171
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0210
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0171
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0210
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0171
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0210
Epoch 16/500
1/1 

In [17]:
model.predict(x=np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[19.09828]], dtype=float32)

In [18]:
model.compile(optimizer='Adagrad', loss='mean_absolute_error')
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 682ms/step - loss: 0.0210
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.0186
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.0168
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.0154
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0142
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0130
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0120
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.0111
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 0.0102
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0094
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.0086
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0078
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.0071
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0064
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0058
Epoch 16/500
1/1 

In [19]:
model.predict(x=np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step


array([[18.999619]], dtype=float32)

In [22]:
model.compile(optimizer='Adagrad', loss='mean_squared_error')
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 496ms/step - loss: 7.3669e-11
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 7.3669e-11
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 7.3669e-11
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 7.3669e-11
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 7.3669e-11
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 7.3669e-11
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 7.3669e-11
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 7.3669e-11
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 7.3669e-11
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 7.3669e-11
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 7.3669e-11
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 7.3669e-11
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 7.3669e-11
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 7.3669e-11
Epoch 15/500
1/1 ━━━━━━━━━━━

In [23]:
model.predict(x=np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[18.999992]], dtype=float32)

In [24]:
model.compile(optimizer='RMSprop', loss='mean_squared_error')
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 555ms/step - loss: 7.3669e-11
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 4.7433e-08
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 3.0473e-05
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 1.6924e-05
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 3.5104e-06
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 8.3371e-07
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.6605e-07
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 1.0799e-07
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 5.2086e-08
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.9305e-08
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.9816e-08
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1.6890e-08
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 1.8509e-08
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 2.5618e-08
Epoch 15/500
1/1 ━━━━━━━━━━━

In [25]:
model.predict(x=np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step


array([[18.994509]], dtype=float32)

In [26]:
model.compile(optimizer='RMSprop', loss='mean_absolute_error')
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 581ms/step - loss: 0.0012
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0067
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0011
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0032
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0012
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0028
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 8.9582e-04
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0026
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 7.2854e-04
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0025
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 6.2602e-04
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0024
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5.5710e-04
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0023
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 5.0822e-0

In [28]:
model.predict(x=np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([[19.00443]], dtype=float32)

optimizer = 'Adagrad', loss = 'mean_squared_error'